### Health Check
GET http://localhost:8080/health

### Get Recipes
GET http://localhost:8080/recipes

### Create Recipe
PUT http://localhost:8080/recipes/sandwich
Content-Type: application/json

{
  "name": "Brayan's Sandwich Recipe",
  "description": "My first recipe.",
  "time": {
    "prep": "5m",
    "cook": "2m",
    "total": "7m"
  },
  "servings": 1,
  "ingredients": [
    {
      "name": "bread",
      "amount": "4 slices"
    },
    {
      "name": "ham",
      "amount": "2 slices"
    },
    {
      "name": "lettuce",
      "amount": "2 pieces"
    },
    {
      "name": "cheese",
      "amount": "2 slices"
    },
    {
      "name": "bacon",
      "amount": "4 pieces"
    }
  ],
  "instructions": [
    "1. Place bread",
    "2. Place ham",
    "3. Place cheese",
    "4. Place lettuce",
    "5. Place 2 pieces of bacon",
    "6. Repeat for second sandwich"
  ]
}

### Get Recipe
GET http://localhost:8080/recipes/sandwich

### Delete Recipe
DELETE http://localhost:8080/recipes/sandwich

### Unknown Path Check
GET http://localhost:8080/unknown
