### Register a New User
PUT http://localhost:8080/register
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@example.com",
  "password": "securePassword123",
  "profileName": "Test2 Test2"
}

### Login with Existing User
# @name login
PUT http://localhost:8080/login
Content-Type: application/json

{
  "username": "test2",
  "password": "securePassword123"
}


## Get Users (public)
GET http://localhost:8080/users

### Create User (public)
PUT http://localhost:8080/users/johndoe123
Content-Type: application/json

{
  "profileName": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com",
  "password": "securepassword123"
}

### Get User (private)
GET http://localhost:8080/users/johndoe1234
Authorization: Bearer {{login.response.body.$.token}}


### Delete User (private)
DELETE http://localhost:8080/users/test2
Authorization: Bearer {{login.response.body.$.token}}