### Get Users
GET https://qooked.azurewebsites.net/users

### Create User
PUT https://qooked.azurewebsites.net/users/123e4567-e8
Content-Type: application/json

{
  "userId": "123e4567-e8",
  "name": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com",
  "password": "securepassword123"
}

### Get User
GET https://qooked.azurewebsites.net/users/123e4567-e8

### Delete User
DELETE https://qooked.azurewebsites.net/users/123e4567-e8
