### Create User
PUT http://localhost:8080/users/johndoe123
Content-Type: application/json

{
  "profileName": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com",
  "password": "securepassword123"
}

### Get Recipes
GET http://localhost:8080/users/johndoe123/recipes

### Create Recipe
PUT http://localhost:8080/users/johndoe123/recipes/sandwichRecipe
Content-Type: application/json

{
  "name": "sandwichRecipe",
  "description": "My first recipe.",
  "time": {
    "prep": "5m",
    "cook": "2m",
    "total": "7m"
  },
  "servings": 1,
  "ingredients": [
    {
      "name": "bread",
      "amount": "4 slices"
    },
    {
      "name": "ham",
      "amount": "3 slices"
    },
    {
      "name": "lettuce",
      "amount": "2 pieces"
    },
    {
      "name": "cheese",
      "amount": "2 slices"
    },
    {
      "name": "bacon",
      "amount": "2 pieces"
    }
  ],
  "instructions": [
    "1. Place bread",
    "2. Place ham",
    "3. Place cheese",
    "4. Place lettuce",
    "5. Place 2 pieces of bacon",
    "6. Repeat for second sandwich"
  ]
}

### Get Recipe
GET http://localhost:8080/users/johndoe123/recipes/sandwichRecipe

### Delete Recipe
DELETE http://localhost:8080/users/johndoe123/recipes/sandwichRecipe

### Delete User
DELETE http://localhost:8080/users/johndoe123