name: Auto-Fix Code Formatting

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref_name }} 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Format code with gofmt
      run: gofmt -w .

    - name: Commit formatting changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Formatting changes detected. Committing..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto-fix code formatting"
          git push origin $GITHUB_REF_NAME
        else
          echo "No formatting changes detected. Skipping commit."
        fi
