name: Infra Deployment using ARM Templates
on: workflow_dispatch

env:
  TEMPLATE_FILE_PATH: ./.infra/Infra.Template.json
  PARAMETERS_FILE_PATH: ./.infra/Infra.Parameters.json

permissions:
  id-token: write
  contents: read
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure w/ service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM templates
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ${{ env.TEMPLATE_FILE_PATH }}
          parameters: ${{ env.PARAMETERS_FILE_PATH }}

      - name: App Service Name
        run: echo ${{ steps.deploy.outputs.appServiceName }}
