name: ARM Template Infra Deployment
on: workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs:
  deploy-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure w/ service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM templates
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infra/Infra.Template.json
          parameters: ./infra/Infra.Parameters.json

      - name: App Service Plan Name
        run: echo ${{ steps.deploy.outputs.appServicePlanName }}
      - name: App Service Name
        run: echo ${{ steps.deploy.outputs.appServiceName }}
      - name: Container Registry Name
        run: echo ${{ steps.deploy.outputs.containerRegistryName }}
