name: Deploy API to Azure Web App
on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: qooked
  WORKING_DIRECTORY: ./src

permissions:
  id-token: write
  contents: read
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: Authenticate to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker Build & Push to ACR
        run: |
          docker build ${{ env.WORKING_DIRECTORY }} -t ${{ secrets.REGISTRY_URL }}/qooked:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URL }}/qooked:${{ github.sha }}

  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure w/ service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set web app ACR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "DOCKER_REGISTRY_SERVER_URL",
                "value": "https://${{ secrets.REGISTRY_URL }}"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                "value": "${{ secrets.REGISTRY_USERNAME  }}"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                "value": "${{ secrets.REGISTRY_PASSWORD }}"
              }
            ]

      - name: Deploy to Azure web app
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_URL }}/qooked:${{ github.sha }}
          # startup-command: './qooked'
